import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { writeSecureFile } from "./secure-file.js";

/**
 * Configures the Gemini CLI the same way the MaxPlus one-line installer
 * (gemini-install.sh) does:
 *
 * 1. Write `~/.gemini/.env` with the Gemini API env vars (GEMINI_API_KEY,
 *    GOOGLE_GEMINI_BASE_URL, GOOGLE_GENAI_USE_VERTEXAI=false, GEMINI_MODEL).
 *    GOOGLE_API_KEY is intentionally omitted to avoid Gemini CLI
 *    duplicate-key warnings (installer parity).
 * 2. Merge `~/.gemini/settings.json` to select the `gemini-api-key` auth
 *    mode, preserving every unrelated setting the user already has.
 *
 * The pool-scoped base URL follows gemini-install.sh: `gemini` uses the
 * endpoint root, any other pool path is appended (`{endpoint}/{pool}`) and
 * must never carry a `/v1beta` suffix — the CLI appends that itself.
 */

export interface GeminiConfigInput {
  /** Primary API key (ccsk-...). */
  apiKey: string;
  /** Endpoint root WITHOUT /v1, e.g. https://api.maxplus-ai.cc */
  endpoint: string;
  /** Pool path for the base URL (e.g. "gemini", "gemini-lite", a Channel slug). */
  pool: string;
  /** Model id to configure, e.g. gemini-3-flash. */
  model: string;
}

export const GEMINI_AUTH_TYPE = "gemini-api-key";

/** The exact pool base URL gemini-install.sh derives (no /v1beta suffix). */
export function geminiBaseUrl(endpoint: string, pool: string): string {
  const base = endpoint.replace(/\/+$/, "");
  return pool === "gemini" ? base : `${base}/${pool}`;
}

export function renderGeminiEnv(input: GeminiConfigInput): string {
  return [
    "# Generated by MaxPlus AI (maxplus-ai) - rerun `maxplus-ai` to refresh.",
    "# Important: GOOGLE_GEMINI_BASE_URL is the selected pool base. Do not append /v1beta.",
    "# GOOGLE_API_KEY is intentionally omitted to avoid Gemini CLI duplicate-key warnings.",
    `GEMINI_API_KEY=${input.apiKey}`,
    `GOOGLE_GEMINI_BASE_URL=${geminiBaseUrl(input.endpoint, input.pool)}`,
    "GOOGLE_GENAI_USE_VERTEXAI=false",
    `GEMINI_MODEL=${input.model}`,
    "",
  ].join("\n");
}

export class GeminiConfigService {
  readonly envPath: string;
  readonly settingsPath: string;

  constructor(paths?: { envPath?: string; settingsPath?: string }) {
    const geminiHome = join(homedir(), ".gemini");
    this.envPath = paths?.envPath ?? join(geminiHome, ".env");
    this.settingsPath = paths?.settingsPath ?? join(geminiHome, "settings.json");
  }

  async apply(input: GeminiConfigInput): Promise<string[]> {
    // 1. ~/.gemini/.env — API key + pool base URL + default model.
    await writeSecureFile(this.envPath, renderGeminiEnv(input));

    // 2. ~/.gemini/settings.json — merge-only auth-mode selection. A file
    //    that fails to parse is never clobbered (same refusal as the other
    //    config writers): the user fixes it, then reruns.
    let settings: Record<string, unknown> = {};
    try {
      const parsed: unknown = JSON.parse(await readFile(this.settingsPath, "utf8"));
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        throw new Error("root must be an object");
      }
      settings = parsed as Record<string, unknown>;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw new Error(
          `${this.settingsPath} is not valid JSON - fix it before switching pools`
        );
      }
    }

    const security = { ...(settings.security as Record<string, unknown> | undefined) };
    const auth = { ...(security.auth as Record<string, unknown> | undefined) };
    auth.selectedType = GEMINI_AUTH_TYPE;
    security.auth = auth;
    settings.security = security;

    await writeSecureFile(this.settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    return [this.envPath, this.settingsPath];
  }
}
