import assert from "node:assert/strict";
import { mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  CodexConfigService,
  mergeCodexToml,
  CODEX_SCALARS_MARKER_START,
  CODEX_SCALARS_MARKER_END,
  CODEX_PROVIDER_MARKER_START,
  CODEX_PROVIDER_MARKER_END,
} from "../dist/services/codex-config.js";

test("Codex merge writes managed regions into an empty config", () => {
  const merged = mergeCodexToml("", {
    apiKey: "test-key",
    endpoint: "https://gateway.example.com",
    model: "gpt-5.6-sol",
  });

  assert.match(merged, new RegExp(`^${CODEX_SCALARS_MARKER_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`));
  assert.match(merged, /model_provider = "cli-hop"\nmodel = "gpt-5\.6-sol"/);
  assert.match(merged, /\[model_providers\.cli-hop\]\nname = "CLI Hop"\nbase_url = "https:\/\/gateway\.example\.com"\nwire_api = "responses"\nrequires_openai_auth = true/);
  assert.ok(merged.trimEnd().endsWith(CODEX_PROVIDER_MARKER_END));
});

test("Codex merge preserves user content and replaces managed regions in place", () => {
  const existing = [
    CODEX_SCALARS_MARKER_START,
    'model_provider = "cli-hop"',
    'model = "old-model"',
    "disable_response_storage = true",
    'model_reasoning_effort = "max"',
    'approval_policy = "never"',
    'sandbox_mode = "danger-full-access"',
    'cli_auth_credentials_store = "file"',
    CODEX_SCALARS_MARKER_END,
    "",
    'favorite_color = "teal"',
    "",
    "[mcp_servers.github]",
    'command = "gh-adapter"',
    "",
    CODEX_PROVIDER_MARKER_START,
    "[model_providers.cli-hop]",
    'name = "CLI Hop"',
    'base_url = "https://old.example.com"',
    'wire_api = "responses"',
    "requires_openai_auth = true",
    CODEX_PROVIDER_MARKER_END,
    "",
  ].join("\n");

  const merged = mergeCodexToml(existing, {
    apiKey: "test-key",
    endpoint: "https://gateway.example.com",
    model: "gpt-5.6-sol",
  });

  assert.equal(merged.match(new RegExp(CODEX_SCALARS_MARKER_START, "g"))?.length, 1);
  assert.equal(merged.match(new RegExp(CODEX_PROVIDER_MARKER_START, "g"))?.length, 1);
  assert.equal(merged.includes("old-model"), false);
  assert.equal(merged.includes("https://old.example.com"), false);
  assert.equal(merged.includes('favorite_color = "teal"'), true);
  assert.equal(merged.includes("[mcp_servers.github]"), true);
  assert.match(merged, /model = "gpt-5\.6-sol"/);
  assert.match(merged, /base_url = "https:\/\/gateway\.example\.com"/);
});

test("Codex merge removes user-copied installer output that would duplicate managed keys", () => {
  const existing = [
    "# Generated by CLI Hop installer (2026-01-01T00:00:00Z)",
    'model_provider = "cli-hop"',
    'model = "gpt-5.6-sol"',
    "disable_response_storage = true",
    'model_reasoning_effort = "max"',
    'approval_policy = "never"',
    'sandbox_mode = "danger-full-access"',
    'cli_auth_credentials_store = "file"',
    "",
    "[model_providers.cli-hop]",
    'name = "CLI Hop"',
    'base_url = "https://api.cli-hop.cc"',
    'wire_api = "responses"',
    "requires_openai_auth = true",
    "",
    "[profiles.work]",
    'model = "work-model"',
  ].join("\n");

  const merged = mergeCodexToml(existing, {
    apiKey: "test-key",
    endpoint: "https://gateway.example.com",
    model: "gpt-5.6-sol",
  });

  assert.equal(merged.match(/^model_provider = /gm)?.length, 1);
  assert.equal(merged.match(/^\[model_providers\.cli-hop\]$/gm)?.length, 1);
  assert.equal(merged.includes("[profiles.work]"), true);
  assert.equal(merged.includes('model = "work-model"'), true);
});

test("Codex config service deploys config.toml, profile, and auth.json with owner-only permissions", async () => {
  const codexHome = join(await mkdtemp(join(tmpdir(), "cli-hop-codex-")), ".codex");

  const changed = await new CodexConfigService(codexHome).apply({
    apiKey: "test-key",
    endpoint: "https://gateway.example.com",
    model: "gpt-5.6-sol",
  });

  assert.deepEqual(changed, [
    join(codexHome, "config.toml"),
    join(codexHome, "cli-hop.config.toml"),
    join(codexHome, "auth.json"),
  ]);

  const auth = JSON.parse(await readFile(join(codexHome, "auth.json"), "utf8"));
  assert.equal(auth.OPENAI_API_KEY, "test-key");
  assert.equal((await stat(join(codexHome, "auth.json"))).mode & 0o777, 0o600);
  assert.equal((await stat(join(codexHome, "config.toml"))).mode & 0o777, 0o600);
  assert.equal((await stat(codexHome)).mode & 0o777, 0o700);

  const profile = await readFile(join(codexHome, "cli-hop.config.toml"), "utf8");
  assert.equal(profile.includes("[model_providers"), false);
  assert.match(profile, /model = "gpt-5\.6-sol"/);
});

test("Codex config service honors a pre-existing config and re-runs idempotently", async () => {
  const codexHome = join(await mkdtemp(join(tmpdir(), "cli-hop-codex-")), ".codex");
  const service = new CodexConfigService(codexHome);
  const input = { apiKey: "test-key", endpoint: "https://gateway.example.com", model: "m" };

  await service.apply(input);
  const first = await readFile(service.configPath, "utf8");
  await writeFile(join(codexHome, "notes.toml"), "unrelated = true\n");

  await service.apply(input);
  const second = await readFile(service.configPath, "utf8");
  assert.equal(second, first);
});
