import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  GeminiConfigService,
  GEMINI_AUTH_TYPE,
  geminiBaseUrl,
  renderGeminiEnv,
} from "../dist/services/gemini-config.js";

test("gemini env mirrors gemini-install.sh exactly", () => {
  const env = renderGeminiEnv({
    apiKey: "ccsk-test",
    endpoint: "https://api.maxplus-ai.cc",
    pool: "gemini",
    model: "gemini-3-flash",
  });
  const lines = env.split("\n");
  assert.match(lines[0], /^# Generated by MaxPlus AI/);
  assert.equal(lines.includes("GEMINI_API_KEY=ccsk-test"), true);
  assert.equal(lines.includes("GOOGLE_API_KEY=ccsk-test"), true);
  assert.equal(lines.includes("GOOGLE_GEMINI_BASE_URL=https://api.maxplus-ai.cc"), true);
  assert.equal(lines.includes("GOOGLE_GENAI_USE_VERTEXAI=false"), true);
  assert.equal(lines.includes("GEMINI_MODEL=gemini-3-flash"), true);
  // Installer parity: GOOGLE_API_KEY is now included (Gemini CLI reads it),
  // and the base URL never carries a /v1beta suffix (the CLI appends it).
  assert.equal(lines.some((l) => l.startsWith("GOOGLE_API_KEY=")), true);
  assert.equal(
    lines.some((l) => !l.startsWith("#") && l.includes("/v1beta")),
    false
  );
});

test("geminiBaseUrl appends non-default pool paths without /v1beta", () => {
  assert.equal(geminiBaseUrl("https://api.maxplus-ai.cc/", "gemini"), "https://api.maxplus-ai.cc");
  assert.equal(
    geminiBaseUrl("https://api.maxplus-ai.cc", "gemini-lite"),
    "https://api.maxplus-ai.cc/gemini-lite"
  );
  assert.equal(
    geminiBaseUrl("https://api.maxplus-ai.cc", "my-channel"),
    "https://api.maxplus-ai.cc/my-channel"
  );
});

test("Gemini config service writes .env and merges auth into an existing settings.json", async () => {
  const geminiHome = join(await mkdtemp(join(tmpdir(), "maxplus-gemini-")), ".gemini");
  const settingsPath = join(geminiHome, "settings.json");
  await mkdir(geminiHome, { recursive: true });
  await writeFile(
    settingsPath,
    JSON.stringify({ theme: "auto", security: { auth: { selectedType: "oauth-personal" }, folderTrust: true } })
  );
  const changed = await new GeminiConfigService({
    envPath: join(geminiHome, ".env"),
    settingsPath,
  }).apply({
    apiKey: "ccsk-test",
    endpoint: "https://gateway.example.com",
    pool: "gemini",
    model: "gemini-3-flash",
  });

  assert.deepEqual(changed, [join(geminiHome, ".env"), settingsPath]);

  const env = await readFile(join(geminiHome, ".env"), "utf8");
  assert.match(env, /^GEMINI_API_KEY=ccsk-test$/m);
  assert.match(env, /^GOOGLE_API_KEY=ccsk-test$/m);
  assert.match(env, /^GOOGLE_GEMINI_BASE_URL=https:\/\/gateway\.example\.com$/m);
  assert.match(env, /^GEMINI_MODEL=gemini-3-flash$/m);

  const settings = JSON.parse(await readFile(settingsPath, "utf8"));
  assert.equal(settings.theme, "auto");
  assert.equal(settings.security.folderTrust, true);
  assert.equal(settings.security.auth.selectedType, GEMINI_AUTH_TYPE);

  // Secrets and configs are owner-only (repo-wide invariant).
  assert.equal((await stat(join(geminiHome, ".env"))).mode & 0o777, 0o600);
  assert.equal((await stat(settingsPath)).mode & 0o777, 0o600);
});

test("Gemini config service creates settings.json when missing and reruns idempotently", async () => {
  const geminiHome = join(await mkdtemp(join(tmpdir(), "maxplus-gemini-")), ".gemini");
  const service = new GeminiConfigService({ envPath: join(geminiHome, ".env"), settingsPath: join(geminiHome, "settings.json") });
  const input = {
    apiKey: "ccsk-test",
    endpoint: "https://gateway.example.com",
    pool: "gemini",
    model: "gemini-3-flash",
  };

  await service.apply(input);
  const first = await readFile(service.settingsPath, "utf8");
  await service.apply(input);
  const second = await readFile(service.settingsPath, "utf8");
  assert.equal(first, second);
  assert.deepEqual(JSON.parse(second).security.auth.selectedType, GEMINI_AUTH_TYPE);
});

test("Gemini config service refuses to overwrite malformed settings.json", async () => {
  const geminiHome = join(await mkdtemp(join(tmpdir(), "maxplus-gemini-")), ".gemini");
  const settingsPath = join(geminiHome, "settings.json");
  await mkdir(geminiHome, { recursive: true });
  await writeFile(settingsPath, "{ malformed");

  await assert.rejects(
    new GeminiConfigService({ settingsPath }).apply({
      apiKey: "ccsk-test",
      endpoint: "https://gateway.example.com",
      pool: "gemini",
      model: "gemini-3-flash",
    }),
    /is not valid JSON - fix it before switching pools/
  );
  // The broken file is untouched - the user fixes it, we never clobber.
  assert.equal(await readFile(settingsPath, "utf8"), "{ malformed");
});
